---
- name: OpenVPN | package | Install required packages
  package:
    name: "{{ item }}"
  with_items: "{{ required_packages }}"
  register: install_required_result
  until: install_required_result is success
  retries: 5
  delay: 5
  tags:
    - skip_ansible_lint

#- name: OpenVPN | package | Install pexpect via pip
#  shell: pip3 install pexpect
